<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.13">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>validation_report_cli_v3.6.4 – pharmapkgs: riskreports</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-d191db7fc3c3d9a11a0015f971215285.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-d191db7fc3c3d9a11a0015f971215285.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-4155540381b49a91af01653b41d53e74.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-550fc17191dd18cbea4970ed4e279535.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">pharmapkgs: riskreports</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/pharmaR/pharmapkgs"> <i class="bi bi-github" role="img" aria-label="GitHub repo">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="validation-report---cli3.6.4" class="level1">
<h1>Validation Report - cli@3.6.4</h1>
</section>
<section id="context" class="level1">
<h1>Context</h1>
<p>This report is fully automated and builds on rhub/ref-image image. Documents the installation of this package on an open source R environment, focusing on:</p>
<ul>
<li>Installation environment description</li>
<li>Testing coverage</li>
</ul>
<p>It is limited to assess whether unit tests and documentation are present and can execute without error. An assessment would be required that the tests and documentation are meaningful.</p>
</section>
<section id="package-cli" class="level1">
<h1>Package cli</h1>
<section id="metric-based-risk-assessment" class="level2">
<h2 class="anchored" data-anchor-id="metric-based-risk-assessment">Metric based risk assessment</h2>
<p>The following metrics are derived from the <code>riskmetric</code> R package.</p>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td style="text-align: left;">has_news</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">news_current</td>
<td style="text-align: left;">TRUE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">exported_namespace</td>
<td style="text-align: left;">240</td>
</tr>
<tr class="even">
<td style="text-align: left;">has_vignettes</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">export_help</td>
<td style="text-align: left;">240</td>
</tr>
<tr class="even">
<td style="text-align: left;">has_website</td>
<td style="text-align: left;">TRUE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">has_maintainer</td>
<td style="text-align: left;">Gábor Csárdi <a href="mailto:gabor@posit.co" class="email">gabor@posit.co</a></td>
</tr>
<tr class="even">
<td style="text-align: left;">bugs_status</td>
<td style="text-align: left;">subscript out of bounds</td>
</tr>
<tr class="odd">
<td style="text-align: left;">has_source_control</td>
<td style="text-align: left;">https://github.com/r-lib/cli</td>
</tr>
<tr class="even">
<td style="text-align: left;">has_bug_reports_url</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">downloads_1yr</td>
<td style="text-align: left;">18648634</td>
</tr>
<tr class="even">
<td style="text-align: left;">reverse_dependencies</td>
<td style="text-align: left;">990</td>
</tr>
<tr class="odd">
<td style="text-align: left;">has_examples</td>
<td style="text-align: left;">0.9159664</td>
</tr>
<tr class="even">
<td style="text-align: left;">dependencies</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">license</td>
<td style="text-align: left;">MIT + file LICENSE</td>
</tr>
</tbody>
</table>
<p><strong>Package general assessment:</strong> Coverage, check results, size, download the last year, reverse dependencies and number of dependencies.</p>
</section>
<section id="dependencies" class="level2">
<h2 class="anchored" data-anchor-id="dependencies">Dependencies</h2>
<p>Overall the package has these dependencies:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">package</th>
<th style="text-align: left;">type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">utils</td>
<td style="text-align: left;">Imports</td>
</tr>
</tbody>
</table>
<p><strong>Package dependencies</strong></p>
</section>
<section id="reverse-dependencies" class="level2">
<h2 class="anchored" data-anchor-id="reverse-dependencies">Reverse dependencies</h2>
<p>Overall the package has 990 reverse dependencies:</p>
<p>AcceptReject, actxps, admiral, admiraldev, admiralmetabolic, admiralonco, admiralophtha, admiralpeds, afcharts, AFR, ageutils, agua, airnow, alarmdata, alcyon, alien, allcontributors, allofus, almanac, alookr, AlpsNMR, altdoc, AMR, anabel, Andromeda, antaresEditObject, ao, apache.sedona, apollo, appsheet, arcgisgeocode, arcgislayers, arcgisplaces, arcgisutils, archive, arrow, artpack, asciicast, askgpt, assertions, atena, ATQ, atrrr, attachment, augmentedRCBD, autoimport, autoslider.core, autovi, available, babelmixr2, baf, bage, baguette, bambooHR, bandicoot, bartMan, baRulho, baseballr, basedosdados, basket, BatchGetSymbols, BATSS, BayesERtools, BayesianReasoning, BayLum, bbw, bcdata, BCEA, beastt, beer, bigrquery, BiocBook, BiocCheck, biocompute, biocroxytest, biodosetools, birdie, bittermelon, bonsai, box.linters, box.lsp, brada, brickster, broom.helpers, brulee, bsicons, bskyr, bullseye, bupaR, bupaverse, butcher, cabinets, cache, calendar, callr, camtrapdp, cancerscreening, cards, cardx, cartographer, cartographr, cascadess, catfun, cbioportalR, ccdR, CDMConnector, cellKey, cellxgenedp, censo2017, censored, cffr, chattr, cheatsheet, checked, checker, checkglobals, checkhelper, checkthat, chess, circle, cito, cliapp, climaemet, clinicalsignificance, clock, cloudfs, cloudstoR, clustlearn, ClustMC, cmdfun, cmmr, cocoon, codebreaker, CodelistGenerator, codemetar, CohortCharacteristics, CohortConstructor, CohortSurvival, CohortSymmetry, coinmarketcapr, compdb, comtradr, concordexR, condathis, conflicted, conformalbayes, congress, connectcreds, constructive, contrastable, cookiemonster, cookies, correlationfunnel, coursekata, covid19india, covidmx, covtracer, cpp11, creditmodel, creepyalien, crew, crew.aws.batch, cricketdata, crisprVerse, CrossClustering, crosshap, crossmap, crosstable, crumble, crypto2, cryptoQuotes, cSEM, csranks, csvwr, cTOST, ctxR, cubble, CuratedAtlasQueryR, cvap, cvasi, cvdprevent, CVXR, czso, dabestr, daiR, DanielBiostatistics10th, dar, dartRverse, dataclass, DataPackageR, dataquieR, dataset, dawaR, dbplyr, debkeepr, deeptime, densityarea, desc, DescrTab2, descstat, DescTools, desk, devtools, DiagrammeR, dials, diffmatchpatch, DImodelsMulti, DImodelsVis, dipsaus, distops, divent, diveR, dm, dockerfiler, doctest, dotprofile, dpkg, dplyr, drake, DrugUtilisation, DSI, dsTidyverse, dsTidyverseClient, dtplyr, duckplyr, dverse, dynamite, DynForest, easycensus, easydb, easysurv, EDCimport, edeaR, edibble, edwards97, EFAtools, ellmer, embed, emuR, enderecobr, envstat, envvar, eodhdR2, eph, epicmodel, epidatr, EpiForsk, EpiNow2, epiparameter, epizootic, eplusr, epwshiftr, euroleaguer, evalITR, excluder, ExclusionTable, executablePackeR, experiences, explore, expstudy, extractox, exuber, exvatools, eye, f1dataR, FaaSr, faers, FastRet, fastRhockey, FastUtils, fauxnaif, favawesome, fdacluster, fdasrvf, FeatureExtraction, feltr, ferrn, ffscrapr, FFTrees, fgeo, fHMM, fiery, findSVI, finetune, finnts, fio, firebase, fitlandr, fitzRoy, flashr, fledge, flipr, FMAT, fmeffects, fmpapi, foghorn, forcats, FoReco, formods, fpp2, fpp3, fr, frenchdata, frictionless, froggeR, funkyheatmap, funModeling, fusen, future.tests, GA, galah, galigor, gargle, gDNAx, GDPuc, gemini.R, genieBPC, geocodebr, geomander, geosapi, geslaR, getProxy, GetTDData, gg1d, ggalign, gganimate, ggarrow, ggautomap, ggbeeswarm, ggborderline, ggdist, ggetho, ggfittext, ggforce, ggfoundry, ggfun, ggh4x, ggip, ggiraph, gglogger, ggmap, ggmapinset, ggmice, ggmulti, ggpath, ggpattern, ggplot2, ggpolar, ggrain, ggraph, ggreveal, ggsc, ggseqplot, ggshadow, ggside, ggstackplot, ggstance, ggstar, ggstats, ggsurveillance, ggsurvfit, ggtangle, ggtree, ggtreeExtra, ggtricks, gh, ghclass, gitignore, GitStats, gittargets, glossr, gmailr, golem, googleAnalyticsR, googleAuthR, googleCloudStorageR, googledrive, googlePubsubR, googlesheets4, govinfoR, gptstudio, gptzeror, gratia, greatR, greed, greta, greta.dynamics, greta.gam, greta.gp, grwat, GSVA, gt, gtable, gtexr, gtExtras, gtfsrouter, gtfstools, gtreg, gtsummary, guideR, gutenbergr, halfmoon, hardhat, haven, hdImpute, healthyverse, heemod, heumilkr, hfhub, highlighter, hoopR, httr2, hubEnsembles, hubUtils, hypr, ibawds, icecream, ife, igraph, ijtiff, incase, IncidencePrevalence, indiedown, infer, inferCSN, Infusion, innsight, interactions, invivoPKfit, ipaddress, iraceplot, itscalledsoccer, iucnr, japanstat, JBrowseR, jinjar, jlmerclusterperm, jmastats, jobqueue, JointFPM, jot, joyn, jpcity, jpgrid, jsonstat, jstor, jtools, karyotapR, keras3, keyATM, khisr, kisopenapi, labelled, labNorm, laminr, landscapemetrics, lava, lcsm, LearnSL, LearnVizLMM, legendry, leprechaun, lgr, lifecycle, linne, lintr, lmtp, log, loon.ggplot, lsasim, lubrilog, luz, MachineShop, maestro, makepipe, mall, MAMS, manydata, manynet, mappoly, mapscanner, MarginalMediation, mark, marquee, maskr, matchedcc, matchmaker, matrixset, mclustAddons, mctq, md4r, measr, measurementProtocol, medfateland, meltr, mergenstudio, metabolic, metasnf, meteoland, meteospain, MicrobiotaProcess, microinverterdata, midi, migrate, miniLNM, mirai, mlbplotR, mlmpower, mlr3summary, mlr3superlearner, mmrm, modeldb, modelenv, modeltime, modeltime.ensemble, modeltime.resample, modisfast, moexer, MoleculeExperiment, MolgenisArmadillo, monolix2rx, MOODE, moodleR, move2, mpactr, mpathr, mpathsenser, msSPChelpR, mtscr, multidplyr, multimedia, mutationtypes, naijR, name, namer, naniar, NanoMethViz, nasapower, navigatr, nblR, ncaavolleyballr, ncodeR, nestedmodels, nevada, nflfastR, nflplotR, nflreadr, nflseedR, nflverse, ngramr, nichetools, nlmixr2, nlmixr2est, nlmixr2extra, nlmixr2lib, nlmixr2rpt, nls.multstart, nonmem2rx, nuggets, nuts, octopusR, odbc, odbr, oddsapiR, oeli, officer, ohun, oldr, OlinkAnalyze, omock, omopgenerics, OmopSketch, OmopViewer, oolong, openair, openairmaps, opendataformat, openFDA, openscoring, openVA, oppr, optedr, optimizeR, orbital, origin, otargen, oysteR, packagepal, packer, pacta.multi.loanbook, pak, palette, palettes, PaRe, pargasite, parquetize, parsermd, parsnip, patchwork, PatientProfiles, PhenotypeR, PhIPData, photon, phsmethods, phylepic, phylosamp, piecemaker, PieGlyph, piggyback, pillar, pins, pioneeR, pixelpuzzle, pkgbuild, pkgcache, pkgdepends, pkgdown, pkgload, PL94171, planscorer, PlotFTIR, plotor, plutor, plyxp, pointblank, poldis, polmineR, poputils, portalr, powerjoin, powRICLPM, ppgmmga, precommit, precondition, preregr, prioritizr, prismatic, probably, processmapR, processpredictR, processx, prodigenr, proffer, progressr, prompt, ProTrackR2, proverbs, prqlr, prt, psmineR, psychmeta, psychReport, PsychWordVec, PurpleAir, purrr, pushoverr, pvda, pysparklyr, quadVAR, qualtRics, quarto, r5r, racademyocean, ractivecampaign, raer, rairtable, ramlegacy, raqs, rayrender, rayvertex, rbiom, rcites, rcmdcheck, RcppJagger, rDataPipeline, rdeps, rdhs, rdlearn, Rduinoiot, react, readapra, readMDTable, readr, rebib, recforest, recipes, REDCapDM, REDCapTidieR, redist, redistmetrics, redistverse, regressinator, renv, reprex, reproducible, resmush, resquin, restez, rethnicity, reticulate, rextendr, RFishBC, rfm, rfold, RGAN, rgee, rgeomstats, rgoogleads, rhino, rhub, ricu, riem, ringostat, rJavaEnv, rjsoncons, rjtools, rlang, rliger, rlinkedinads, rmdl, rmweather, robotoolbox, Rogue, rollama, romic, ropenblas, roundwork, roxygen2, roxygen2md, roxylint, roxytypes, rpostgis, RprobitB, rredlist, rsample, rsconnect, RSQLite, rstudio.prefs, rsurveycto, rtgstat, rticulate, ruminate, rvec, rvest, rwarrior, rWCVP, rxode2, rytstat, s3, sae.projection, saeHB.unit, saens, safetensors, saros, saros.base, sars, sbo, sbtools, scales, scatterpie, scCustomize, scDotPlot, scenes, scFeatures, scorecard, scoringutils, SCORPION, SCpubr, scregclust, scrutiny, sdcHierarchies, sdcLog, sdmTMB, SDMtune, sdtm.oak, seahtrue, segclust2d, selenider, sendgridr, seqArchR, seqArchRplus, sequoia, serocalculator, sessioninfo, settingsSync, sevenbridges2, sever, sewage, sfd, sfdep, shapr, shide, shiny2docker, shinyExprPortal, shinylive, shinyloadtest, shinyMixR, shinyMobile, shinyquiz, SIAmodules, SIAtools, siconvr, sigminer, SimDesign, sinew, SIPDIBGE, sits, sjSDM, sketchy, skimr, skpr, slap, slider, snvecR, SomaDataIO, SpaDES.core, sparsegl, sparsevctrs, spdesign, speakr, spicyR, spotoroo, sqltargets, squat, srcpkgs, sreg, srppp, sspm, staccuracy, stacks, stagedtrees, starter, STATcubeR, statnipokladna, stbl, stenR, SticsRFiles, stochLAB, stoRy, streamy, streetscape, string2path, stringr, styler, sudachir, suddengains, summclust, supernova, surveydown, susographql, svMisc, sweater, tablexlsx, tabulate, tabxplor, tada, targets, taxa, taxize, taylor, teal.code, TestGenerator, testthat, texor, text2speech, textrecipes, tfevents, tglkmeans, thaipdf, themis, TheOpenAIR, theorytools, thinkr, tibble, tibblify, tidybayes, tidychangepoint, tidyclust, tidycmprsk, tidyCoverage, tidydelta, tidyEdSurvey, tidyfinance, tidygam, tidygraph, tidyhydat, tidyindex, tidyllm, tidymodels, tidyomics, tidyplots, tidypredict, tidyprompt, tidyquant, tidyr, tidyREDCap, tidyrules, tidyselect, tidyseurat, tidySingleCellExperiment, tidySpatialExperiment, tidysq, tidySummarizedExperiment, tidyterra, tidytext, tidytlg, tidytree, tidytuesdayR, tidyverse, tidywikidatar, timbr, timeplyr, tinytiger, tipr, TITAN2, tmap, tna, tntpr, toposort, torch, trackdown, transx, traudem, TreeDist, treeio, treemapify, TreeMineR, TreeSearch, treesitter, tremendousr, trimmer, trud, tune, TwoWayFEWeights, ubiquity, UnalR, unicol, unikn, updateme, updater, urlchecker, urlshorteneR, usedthese, usemodels, usethis, utf8, uxr, valentine, valr, vcr, vctrs, versus, vetiver, VicmapR, visdat, visOmopResults, vroom, vvauditor, wacolors, waldo, warbleR, washi, wbids, wdpar, webmockr, wehoop, weird, whereami, whippr, whitewater, wikkitidy, worcs, workflows, workflowsets, worldfootballR, wpm, writer, wru, xmap, xml2, xportr, xpose.xtras, yardstick, yfR, yulab.utils, zellkonverter, zen4R, zendown, zenstats, zephyr</p>
</section>
<section id="namespace" class="level2">
<h2 class="anchored" data-anchor-id="namespace">Namespace</h2>
<p>Overall the package has 240 exported objects. 240 are documented:</p>
<pre><code>             __cli_update_due                    ansi_align 
                         TRUE                          TRUE 
                  ansi_chartr                 ansi_collapse 
                         TRUE                          TRUE 
                 ansi_columns                     ansi_grep 
                         TRUE                          TRUE 
                   ansi_grepl                  ansi_has_any 
                         TRUE                          TRUE 
   ansi_has_hyperlink_support              ansi_hide_cursor 
                         TRUE                          TRUE 
                    ansi_html               ansi_html_style 
                         TRUE                          TRUE 
         ansi_hyperlink_types                    ansi_nchar 
                         TRUE                          TRUE 
                  ansi_nzchar             ansi_palette_show 
                         TRUE                          TRUE 
                ansi_palettes                    ansi_regex 
                         TRUE                          TRUE 
             ansi_show_cursor                 ansi_simplify 
                         TRUE                          TRUE 
                  ansi_string                    ansi_strip 
                         TRUE                          TRUE 
                ansi_strsplit                  ansi_strtrim 
                         TRUE                          TRUE 
                 ansi_strwrap                   ansi_substr 
                         TRUE                          TRUE 
               ansi_substring                  ansi_tolower 
                         TRUE                          TRUE 
                 ansi_toupper                   ansi_trimws 
                         TRUE                          TRUE 
      ansi_with_hidden_cursor                      bg_black 
                         TRUE                          TRUE 
                      bg_blue                   bg_br_black 
                         TRUE                          TRUE 
                   bg_br_blue                    bg_br_cyan 
                         TRUE                          TRUE 
                  bg_br_green                 bg_br_magenta 
                         TRUE                          TRUE 
                    bg_br_red                   bg_br_white 
                         TRUE                          TRUE 
                 bg_br_yellow                       bg_cyan 
                         TRUE                          TRUE 
                     bg_green                    bg_magenta 
                         TRUE                          TRUE 
                      bg_none                        bg_red 
                         TRUE                          TRUE 
                     bg_white                     bg_yellow 
                         TRUE                          TRUE 
                         boxx                 builtin_theme 
                         TRUE                          TRUE 
                     cat_boxx                    cat_bullet 
                         TRUE                          TRUE 
                     cat_line                     cat_print 
                         TRUE                          TRUE 
                     cat_rule               ccli_tick_reset 
                         TRUE                          TRUE 
                          cli                     cli_abort 
                         TRUE                          TRUE 
                    cli_alert              cli_alert_danger 
                         TRUE                          TRUE 
               cli_alert_info             cli_alert_success 
                         TRUE                          TRUE 
            cli_alert_warning                cli_blockquote 
                         TRUE                          TRUE 
                  cli_bullets               cli_bullets_raw 
                         TRUE                          TRUE 
                     cli_code                       cli_div 
                         TRUE                          TRUE 
                       cli_dl                       cli_end 
                         TRUE                          TRUE 
                      cli_fmt                    cli_format 
                         TRUE                          TRUE 
            cli_format_method                        cli_h1 
                         TRUE                          TRUE 
                       cli_h2                        cli_h3 
                         TRUE                          TRUE 
                   cli_inform                        cli_li 
                         TRUE                          TRUE 
              cli_list_themes                        cli_ol 
                         TRUE                          TRUE 
        cli_output_connection                       cli_par 
                         TRUE                          TRUE 
             cli_process_done            cli_process_failed 
                         TRUE                          TRUE 
            cli_process_start            cli_progress_along 
                         TRUE                          TRUE 
             cli_progress_bar cli_progress_builtin_handlers 
                         TRUE                          TRUE 
         cli_progress_cleanup             cli_progress_demo 
                         TRUE                          TRUE 
            cli_progress_done          cli_progress_message 
                         TRUE                          TRUE 
             cli_progress_num           cli_progress_output 
                         TRUE                          TRUE 
            cli_progress_step           cli_progress_styles 
                         TRUE                          TRUE 
          cli_progress_update                      cli_rule 
                         TRUE                          TRUE 
                   cli_sitrep                    cli_status 
                         TRUE                          TRUE 
             cli_status_clear             cli_status_update 
                         TRUE                          TRUE 
                     cli_text                cli_tick_reset 
                         TRUE                          TRUE 
                       cli_ul                       cli_vec 
                         TRUE                          TRUE 
                 cli_verbatim                      cli_warn 
                         TRUE                          TRUE 
               code_highlight               code_theme_list 
                         TRUE                          TRUE 
                    col_black                      col_blue 
                         TRUE                          TRUE 
                 col_br_black                   col_br_blue 
                         TRUE                          TRUE 
                  col_br_cyan                  col_br_green 
                         TRUE                          TRUE 
               col_br_magenta                    col_br_red 
                         TRUE                          TRUE 
                 col_br_white                 col_br_yellow 
                         TRUE                          TRUE 
                     col_cyan                     col_green 
                         TRUE                          TRUE 
                     col_grey                   col_magenta 
                         TRUE                          TRUE 
                     col_none                       col_red 
                         TRUE                          TRUE 
                   col_silver                     col_white 
                         TRUE                          TRUE 
                   col_yellow           combine_ansi_styles 
                         TRUE                          TRUE 
                console_width                   default_app 
                         TRUE                          TRUE 
                demo_spinners                      diff_chr 
                         TRUE                          TRUE 
                     diff_str            format_bullets_raw 
                         TRUE                          TRUE 
                 format_error                 format_inline 
                         TRUE                          TRUE 
               format_message                format_warning 
                         TRUE                          TRUE 
                  get_spinner          has_keypress_support 
                         TRUE                          TRUE 
                  hash_animal                    hash_emoji 
                         TRUE                          TRUE 
                hash_file_md5                hash_file_sha1 
                         TRUE                          TRUE 
             hash_file_sha256              hash_file_xxhash 
                         TRUE                          TRUE 
           hash_file_xxhash64                      hash_md5 
                         TRUE                          TRUE 
              hash_obj_animal                hash_obj_emoji 
                         TRUE                          TRUE 
                 hash_obj_md5                 hash_obj_sha1 
                         TRUE                          TRUE 
              hash_obj_sha256               hash_obj_xxhash 
                         TRUE                          TRUE 
            hash_obj_xxhash64               hash_raw_animal 
                         TRUE                          TRUE 
               hash_raw_emoji                  hash_raw_md5 
                         TRUE                          TRUE 
                hash_raw_sha1               hash_raw_sha256 
                         TRUE                          TRUE 
              hash_raw_xxhash             hash_raw_xxhash64 
                         TRUE                          TRUE 
                    hash_sha1                   hash_sha256 
                         TRUE                          TRUE 
                  hash_xxhash                 hash_xxhash64 
                         TRUE                          TRUE 
                  is_ansi_tty                is_dynamic_tty 
                         TRUE                          TRUE 
               is_utf8_output                      keypress 
                         TRUE                          TRUE 
           list_border_styles                 list_spinners 
                         TRUE                          TRUE 
                 list_symbols               make_ansi_style 
                         TRUE                          TRUE 
                 make_spinner                            no 
                         TRUE                          TRUE 
              num_ansi_colors                        pb_bar 
                         TRUE                          TRUE 
                   pb_current              pb_current_bytes 
                         TRUE                          TRUE 
                   pb_elapsed              pb_elapsed_clock 
                         TRUE                          TRUE 
               pb_elapsed_raw                        pb_eta 
                         TRUE                          TRUE 
                   pb_eta_raw                    pb_eta_str 
                         TRUE                          TRUE 
                     pb_extra                         pb_id 
                         TRUE                          TRUE 
                      pb_name                    pb_percent 
                         TRUE                          TRUE 
                       pb_pid                       pb_rate 
                         TRUE                          TRUE 
                pb_rate_bytes                   pb_rate_raw 
                         TRUE                          TRUE 
                      pb_spin                     pb_status 
                         TRUE                          TRUE 
                 pb_timestamp                      pb_total 
                         TRUE                          TRUE 
               pb_total_bytes                     pluralize 
                         TRUE                          TRUE 
            pretty_print_code                           qty 
                         TRUE                          TRUE 
                         rule                         ruler 
                         TRUE                          TRUE 
                 simple_theme                     spark_bar 
                         TRUE                          TRUE 
                   spark_line                     start_app 
                         TRUE                          TRUE 
                     stop_app                 style_blurred 
                         TRUE                          TRUE 
                   style_bold                     style_dim 
                         TRUE                          TRUE 
                 style_hidden               style_hyperlink 
                         TRUE                          TRUE 
                style_inverse                  style_italic 
                         TRUE                          TRUE 
            style_no_bg_color              style_no_blurred 
                         TRUE                          TRUE 
                style_no_bold                style_no_color 
                         TRUE                          TRUE 
                 style_no_dim               style_no_hidden 
                         TRUE                          TRUE 
             style_no_inverse               style_no_italic 
                         TRUE                          TRUE 
       style_no_strikethrough            style_no_underline 
                         TRUE                          TRUE 
                  style_reset           style_strikethrough 
                         TRUE                          TRUE 
              style_underline                        symbol 
                         TRUE                          TRUE 
                test_that_cli                       ticking 
                         TRUE                          TRUE 
                         tree                     truecolor 
                         TRUE                          TRUE 
               utf8_graphemes                    utf8_nchar 
                         TRUE                          TRUE 
                  utf8_substr                     vt_output 
                         TRUE                          TRUE </code></pre>
<section id="examples" class="level3">
<h3 class="anchored" data-anchor-id="examples">Examples</h3>
<p>There are 109 help pages with examples, from 119 (91.60 %).</p>
</section>
<section id="news" class="level3">
<h3 class="anchored" data-anchor-id="news">NEWS</h3>
<p>The package has NEWS file and it is current.</p>
</section>
<section id="license" class="level3">
<h3 class="anchored" data-anchor-id="license">License</h3>
<p>The package uses .</p>
</section>
</section>
</section>
<section id="installation-environment" class="level1">
<h1>Installation environment</h1>
<section id="system-info" class="level2">
<h2 class="anchored" data-anchor-id="system-info">System Info</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Field</th>
<th style="text-align: left;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Image</td>
<td style="text-align: left;">rhub/ref-image</td>
</tr>
<tr class="even">
<td style="text-align: left;">OS</td>
<td style="text-align: left;">Ubuntu 24.04.1 LTS</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Platform</td>
<td style="text-align: left;">x86_64-pc-linux-gnu</td>
</tr>
<tr class="even">
<td style="text-align: left;">System</td>
<td style="text-align: left;">x86_64, linux-gnu</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Execution Time</td>
<td style="text-align: left;">2025-02-16 04:29:22 UTC</td>
</tr>
</tbody>
</table>
<p><strong>System information</strong>. Table about the system used to check the package.</p>
</section>
<section id="r-session-info" class="level2">
<h2 class="anchored" data-anchor-id="r-session-info">R Session Info</h2>
<p>Information about the R environment and capabilities:</p>
<pre><code>R version 4.4.2 (2024-10-31)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 24.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.26.so;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

time zone: UTC
tzcode source: system (glibc)

attached base packages:
[1] tools     stats     graphics  grDevices utils     datasets  methods  
[8] base     

loaded via a namespace (and not attached):
 [1] riskreports_0.0.0.9003 compiler_4.4.2         fastmap_1.2.0         
 [4] cli_3.6.4              htmltools_0.5.8.1      yaml_2.3.10           
 [7] rmarkdown_2.29         knitr_1.49             jsonlite_1.8.9        
[10] xfun_0.50              digest_0.6.37          rlang_1.1.5           
[13] evaluate_1.0.3        </code></pre>
<p>Platform used:</p>
<pre><code>   OS.type   file.sep dynlib.ext        GUI     endian    pkgType   path.sep 
    "unix"        "/"      ".so"      "X11"   "little"   "source"        ":" 
    r_arch 
        "" </code></pre>
<p>R’s capabilities:</p>
<pre><code>       jpeg         png        tiff       tcltk         X11        aqua 
       TRUE        TRUE        TRUE        TRUE       FALSE       FALSE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE       FALSE        TRUE       FALSE        TRUE 
        NLS       Rprof     profmem       cairo         ICU long.double 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
    libcurl 
       TRUE </code></pre>
<p>External software:</p>
<pre><code>                                                     zlib 
                                                    "1.3" 
                                                    bzlib 
                                     "1.0.8, 13-Jul-2019" 
                                                       xz 
                                                  "5.4.5" 
                                               libdeflate 
                                                   "1.19" 
                                                     PCRE 
                                       "10.42 2022-12-11" 
                                                      ICU 
                                                   "74.2" 
                                                      TRE 
                                "TRE 0.8.0 R_fixes (BSD)" 
                                                    iconv 
                                             "glibc 2.39" 
                                                 readline 
                                                    "8.2" 
                                                     BLAS 
"/usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3" </code></pre>
<p>Graphics external software:</p>
<pre><code>                   cairo                  cairoFT                    pango 
                "1.18.0"                       ""                 "1.52.1" 
                  libpng                     jpeg                  libtiff 
                "1.6.43"                    "8.0" "LIBTIFF, Version 4.5.1" </code></pre>
<p>Numerical characteristics of the machine:</p>
<pre><code>               double.eps            double.neg.eps               double.xmin 
             2.220446e-16              1.110223e-16             2.225074e-308 
              double.xmax               double.base             double.digits 
            1.797693e+308              2.000000e+00              5.300000e+01 
          double.rounding              double.guard         double.ulp.digits 
             5.000000e+00              0.000000e+00             -5.200000e+01 
    double.neg.ulp.digits           double.exponent            double.min.exp 
            -5.300000e+01              1.100000e+01             -1.022000e+03 
           double.max.exp               integer.max               sizeof.long 
             1.024000e+03              2.147484e+09              8.000000e+00 
          sizeof.longlong         sizeof.longdouble            sizeof.pointer 
             8.000000e+00              1.600000e+01              8.000000e+00 
            sizeof.time_t            longdouble.eps        longdouble.neg.eps 
             8.000000e+00              1.084202e-19              5.421011e-20 
        longdouble.digits       longdouble.rounding          longdouble.guard 
             6.400000e+01              5.000000e+00              0.000000e+00 
    longdouble.ulp.digits longdouble.neg.ulp.digits       longdouble.exponent 
            -6.300000e+01             -6.400000e+01              1.500000e+01 
       longdouble.min.exp        longdouble.max.exp 
            -1.638200e+04              1.638400e+04 </code></pre>
<p>Random number generation process:</p>
<pre><code>[1] "Mersenne-Twister" "Inversion"        "Rejection"       </code></pre>
</section>
<section id="information-about-the-environment" class="level2">
<h2 class="anchored" data-anchor-id="information-about-the-environment">Information about the environment</h2>
<p>Environmental and options variables affect how package checks and software in it might behave. Here is the environmental variables when running this report</p>
<pre><code>_R_CHECK_SYSTEM_CLOCK_
                        FALSE
ACCEPT_EULA             Y
ACTIONS_RUNNER_ACTION_ARCHIVE_CACHE
                        /opt/actionarchivecache
AGENT_TOOLSDIRECTORY    /opt/hostedtoolcache
ANDROID_HOME            /usr/local/lib/android/sdk
ANDROID_NDK             /usr/local/lib/android/sdk/ndk/27.2.12479018
ANDROID_NDK_HOME        /usr/local/lib/android/sdk/ndk/27.2.12479018
ANDROID_NDK_LATEST_HOME
                        /usr/local/lib/android/sdk/ndk/27.2.12479018
ANDROID_NDK_ROOT        /usr/local/lib/android/sdk/ndk/27.2.12479018
ANDROID_SDK_ROOT        /usr/local/lib/android/sdk
ANT_HOME                /usr/share/ant
AZURE_EXTENSION_DIR     /opt/az/azcliextensions
BOOTSTRAP_HASKELL_NONINTERACTIVE
                        1
BUNDLE_EXT              linux-amd64.deb
CHROME_BIN              /usr/bin/google-chrome
CHROMEWEBDRIVER         /usr/local/share/chromedriver-linux64
CI                      true
CONDA                   /usr/share/miniconda
DEBIAN_FRONTEND         noninteractive
DENO_DOM_PLUGIN         /opt/quarto/bin/tools/x86_64/deno_dom/libplugin.so
DENO_NO_UPDATE_CHECK    1
DENO_TLS_CA_STORE       system,mozilla
DEPLOYMENT_BASEPATH     /opt/runner
DOTNET_MULTILEVEL_LOOKUP
                        0
DOTNET_NOLOGO           1
DOTNET_SKIP_FIRST_TIME_EXPERIENCE
                        1
EDGEWEBDRIVER           /usr/local/share/edge_driver
EDITOR                  vi
GECKOWEBDRIVER          /usr/local/share/gecko_driver
GHCUP_INSTALL_BASE_PREFIX
                        /usr/local
GITHUB_ACTION           __run
GITHUB_ACTION_REF       
GITHUB_ACTION_REPOSITORY
                        
GITHUB_ACTIONS          true
GITHUB_ACTOR            llrs-roche
GITHUB_ACTOR_ID         185338939
GITHUB_API_URL          https://api.github.com
GITHUB_BASE_REF         
GITHUB_ENV              /home/runner/work/_temp/_runner_file_commands/set_env_6ba12b84-2f44-4ad5-be34-dae80230865f
GITHUB_EVENT_NAME       schedule
GITHUB_EVENT_PATH       /home/runner/work/_temp/_github_workflow/event.json
GITHUB_GRAPHQL_URL      https://api.github.com/graphql
GITHUB_HEAD_REF         
GITHUB_JOB              main
GITHUB_OUTPUT           /home/runner/work/_temp/_runner_file_commands/set_output_6ba12b84-2f44-4ad5-be34-dae80230865f
GITHUB_PATH             /home/runner/work/_temp/_runner_file_commands/add_path_6ba12b84-2f44-4ad5-be34-dae80230865f
GITHUB_REF              refs/heads/main
GITHUB_REF_NAME         main
GITHUB_REF_PROTECTED    false
GITHUB_REF_TYPE         branch
GITHUB_REPOSITORY       pharmaR/pharmapkgs
GITHUB_REPOSITORY_ID    798326913
GITHUB_REPOSITORY_OWNER
                        pharmaR
GITHUB_REPOSITORY_OWNER_ID
                        42115094
GITHUB_RETENTION_DAYS   90
GITHUB_RUN_ATTEMPT      1
GITHUB_RUN_ID           13351230359
GITHUB_RUN_NUMBER       93
GITHUB_SERVER_URL       https://github.com
GITHUB_SHA              b7796ef4941f135c4d61c83d399bb9fa3a477379
GITHUB_STATE            /home/runner/work/_temp/_runner_file_commands/save_state_6ba12b84-2f44-4ad5-be34-dae80230865f
GITHUB_STEP_SUMMARY     /home/runner/work/_temp/_runner_file_commands/step_summary_6ba12b84-2f44-4ad5-be34-dae80230865f
GITHUB_TRIGGERING_ACTOR
                        llrs-roche
GITHUB_WORKFLOW         Update package repositories
GITHUB_WORKFLOW_REF     pharmaR/pharmapkgs/.github/workflows/update-repos.yml@refs/heads/main
GITHUB_WORKFLOW_SHA     b7796ef4941f135c4d61c83d399bb9fa3a477379
GITHUB_WORKSPACE        /home/runner/work/pharmapkgs/pharmapkgs
GOROOT_1_21_X64         /opt/hostedtoolcache/go/1.21.13/x64
GOROOT_1_22_X64         /opt/hostedtoolcache/go/1.22.12/x64
GOROOT_1_23_X64         /opt/hostedtoolcache/go/1.23.6/x64
GRADLE_HOME             /usr/share/gradle-8.12.1
HOME                    /home/runner
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS
                        3650
HOMEBREW_NO_AUTO_UPDATE
                        1
ImageOS                 ubuntu24
ImageVersion            20250209.1.0
INVOCATION_ID           cea0ff53850b49ce839e8b7d02d05041
JAVA_HOME               /usr/lib/jvm/temurin-17-jdk-amd64
JAVA_HOME_11_X64        /usr/lib/jvm/temurin-11-jdk-amd64
JAVA_HOME_17_X64        /usr/lib/jvm/temurin-17-jdk-amd64
JAVA_HOME_21_X64        /usr/lib/jvm/temurin-21-jdk-amd64
JAVA_HOME_8_X64         /usr/lib/jvm/temurin-8-jdk-amd64
JOURNAL_STREAM          8:7454
LANG                    C.UTF-8
LD_LIBRARY_PATH         /opt/R/4.4.2/lib/R/lib:/usr/local/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/temurin-17-jdk-amd64/lib/server:/opt/R/4.4.2/lib/R/lib:/usr/local/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/temurin-17-jdk-amd64/lib/server
LN_S                    ln -s
LOGGER_LOG_LEVEL        DEBUG
MAKE                    make
MEMORY_PRESSURE_WATCH   /sys/fs/cgroup/system.slice/runner-provisioner.service/memory.pressure
MEMORY_PRESSURE_WRITE   c29tZSAyMDAwMDAgMjAwMDAwMAA=
NOT_CRAN                true
NVM_DIR                 /home/runner/.nvm
PAGER                   /usr/bin/pager
PATH                    /snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PERFLOG_LOCATION_SETTING
                        RUNNER_PERFLOG
PHARMAPKGS_EXCLUDED_METRICS
                        assess_covr_coverage,assess_r_cmd_check
PHARMAPKGS_LIMIT        1000
PHARMAPKGS_PLATFORM     ubuntu-22.04
PHARMAPKGS_R_VERSION    4.4
PHARMAPKGS_REMOTE_REPO
                        https://cloud.r-project.org/
PIPX_BIN_DIR            /opt/pipx_bin
PIPX_HOME               /opt/pipx
PKGCACHE_HTTP_VERSION   2
PKGLOAD_PARENT_TEMPDIR
                        /tmp/RtmpCk6Ofc
POWERSHELL_DISTRIBUTION_CHANNEL
                        GitHub-Actions-ubuntu24
PROCESSX_PS1bc3f26eca6_1739680157
                        YES
PWD                     /home/runner/work/pharmapkgs/pharmapkgs
QUARTO_BIN_PATH         /opt/quarto/bin
QUARTO_DENO             /opt/quarto/bin/tools/x86_64/deno
QUARTO_DOCUMENT_PATH    /home/runner/work/pharmapkgs/pharmapkgs/inst/report
QUARTO_PROFILE          
QUARTO_PROJECT_DIR      /home/runner/work/pharmapkgs/pharmapkgs
QUARTO_PROJECT_ROOT     /home/runner/work/pharmapkgs/pharmapkgs
QUARTO_ROOT             /
QUARTO_SHARE_PATH       /opt/quarto/share
R_ARCH                  
R_BROWSER               xdg-open
R_BZIPCMD               /usr/bin/bzip2
R_DOC_DIR               /opt/R/4.4.2/lib/R/doc
R_GZIPCMD               /usr/bin/gzip
R_HOME                  /opt/R/4.4.2/lib/R
R_INCLUDE_DIR           /opt/R/4.4.2/lib/R/include
R_LIB_FOR_PAK           /opt/R/4.4.2/lib/R/site-library
R_LIBS_SITE             /opt/R/4.4.2/lib/R/site-library
R_LIBS_USER             /home/runner/work/_temp/Library
R_PAPERSIZE             letter
R_PAPERSIZE_USER        letter
R_PDFVIEWER             /usr/bin/xdg-open
R_PLATFORM              x86_64-pc-linux-gnu
R_PRINTCMD              /usr/bin/lpr
R_RD4PDF                times,inconsolata,hyper
R_SESSION_TMPDIR        /tmp/RtmpEEMgZu
R_SHARE_DIR             /opt/R/4.4.2/lib/R/share
R_STRIP_SHARED_LIB      strip --strip-unneeded
R_STRIP_STATIC_LIB      strip --strip-debug
R_TEXI2DVICMD           /usr/bin/texi2dvi
R_UNZIPCMD              /usr/bin/unzip
R_ZIPCMD                /usr/bin/zip
RUNNER_ARCH             X64
RUNNER_ENVIRONMENT      github-hosted
RUNNER_NAME             GitHub Actions 9
RUNNER_OS               Linux
RUNNER_PERFLOG          /home/runner/perflog
RUNNER_TEMP             /home/runner/work/_temp
RUNNER_TOOL_CACHE       /opt/hostedtoolcache
RUNNER_TRACKING_ID      github_d0120492-4873-4b13-9ede-fb6d0d82420b
RUNNER_USER             runner
RUNNER_WORKSPACE        /home/runner/work/pharmapkgs
SED                     /usr/bin/sed
SELENIUM_JAR_PATH       /usr/share/java/selenium-server.jar
SGX_AESM_ADDR           1
SHLVL                   1
STATS_D                 true
STATS_D_D               true
STATS_D_TC              true
STATS_EXT               true
STATS_EXTP              https://provjobdprod.z13.web.core.windows.net/settings/provjobdsettings-latest/provjobd.data
STATS_PIP               false
STATS_RDCL              true
STATS_TRP               true
STATS_UE                true
STATS_V3PS              true
STATS_VMD               true
STATS_VMFE              true
SWIFT_PATH              /usr/share/swift/usr/bin
SYSTEMD_EXEC_PID        829
TAR                     /usr/bin/tar
TZ                      UTC
USER                    runner
VCPKG_INSTALLATION_ROOT
                        /usr/local/share/vcpkg
XDG_CONFIG_HOME         /home/runner/.config
XDG_RUNTIME_DIR         /run/user/1001</code></pre>
<p>These are the options set to generate the report:</p>
<pre><code>$add.smooth
[1] TRUE

$bitmapType
[1] "cairo"

$browser
[1] "xdg-open"

$browserNLdisabled
[1] FALSE

$callr.condition_handler_cli_message
function (msg) 
{
    custom_handler &lt;- getOption("cli.default_handler")
    if (is.function(custom_handler)) {
        custom_handler(msg)
    }
    else {
        cli_server_default(msg)
    }
}
&lt;bytecode: 0x55c3dfd34910&gt;
&lt;environment: namespace:cli&gt;

$catch.script.errors
[1] FALSE

$CBoundsCheck
[1] FALSE

$check.bounds
[1] FALSE

$citation.bibtex.max
[1] 1

$continue
[1] "+ "

$contrasts
        unordered           ordered 
"contr.treatment"      "contr.poly" 

$covr.record_tests
[1] TRUE

$defaultPackages
[1] "datasets"  "utils"     "grDevices" "graphics"  "stats"     "methods"  

$demo.ask
[1] "default"

$deparse.cutoff
[1] 60

$device
function (width = 7, height = 7, ...) 
{
    grDevices::pdf(NULL, width, height, ...)
}
&lt;bytecode: 0x55c3df489ec0&gt;
&lt;environment: namespace:knitr&gt;

$device.ask.default
[1] FALSE

$digits
[1] 7

$dvipscmd
[1] "dvips"

$echo
[1] FALSE

$editor
[1] "vi"

$encoding
[1] "native.enc"

$example.ask
[1] "default"

$expressions
[1] 5000

$help.search.types
[1] "vignette" "demo"     "help"    

$help.try.all.packages
[1] FALSE

$htmltools.preserve.raw
[1] TRUE

$HTTPUserAgent
[1] "R/4.4.2 R (4.4.2 x86_64-pc-linux-gnu x86_64 linux-gnu) on GitHub Actions"

$internet.info
[1] 2

$keep.parse.data
[1] TRUE

$keep.parse.data.pkgs
[1] FALSE

$keep.source
[1] FALSE

$keep.source.pkgs
[1] FALSE

$knitr.in.progress
[1] TRUE

$locatorBell
[1] TRUE

$mailer
[1] "mailto"

$matprod
[1] "default"

$max.contour.segments
[1] 25000

$max.print
[1] 99999

$menu.graphics
[1] TRUE

$na.action
[1] "na.omit"

$Ncpus
[1] 1

$nwarnings
[1] 50

$OutDec
[1] "."

$pager
[1] "/opt/R/4.4.2/lib/R/bin/pager"

$papersize
[1] "letter"

$PCRE_limit_recursion
[1] NA

$PCRE_study
[1] FALSE

$PCRE_use_JIT
[1] TRUE

$pdfviewer
[1] "/usr/bin/xdg-open"

$pkgType
[1] "source"

$printcmd
[1] "/usr/bin/lpr"

$prompt
[1] "&gt; "

$repos
                      CRAN 
"https://cran.rstudio.com" 

$rl_word_breaks
[1] " \t\n\"\\'`&gt;&lt;=%;,|&amp;{()}"

$rlang_trace_top_env
&lt;environment: R_GlobalEnv&gt;

$scipen
[1] 0

$show.coef.Pvalues
[1] TRUE

$show.error.messages
[1] TRUE

$show.signif.stars
[1] TRUE

$showErrorCalls
[1] TRUE

$showNCalls
[1] 50

$showWarnCalls
[1] FALSE

$str
$str$strict.width
[1] "no"

$str$digits.d
[1] 3

$str$vec.len
[1] 4

$str$list.len
[1] 99

$str$deparse.lines
NULL

$str$drop.deparse.attr
[1] TRUE

$str$formatNum
function (x, ...) 
format(x, trim = TRUE, drop0trailing = TRUE, ...)
&lt;environment: 0x55c3df20c520&gt;


$str.dendrogram.last
[1] "`"

$texi2dvi
[1] "/usr/bin/texi2dvi"

$tikzMetricsDictionary
[1] "validation_report_cli_v3.6.4-tikzDictionary"

$timeout
[1] 60

$try.outFile
A connection with                    
description ""      
class       "file"  
mode        "w+b"   
text        "binary"
opened      "opened"
can read    "yes"   
can write   "yes"   

$ts.eps
[1] 1e-05

$ts.S.compat
[1] FALSE

$unzip
[1] "/usr/bin/unzip"

$useFancyQuotes
[1] FALSE

$verbose
[1] FALSE

$warn
[1] 0

$warning.length
[1] 1000

$warnPartialMatchArgs
[1] FALSE

$warnPartialMatchAttr
[1] FALSE

$warnPartialMatchDollar
[1] FALSE

$width
[1] 80</code></pre>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/pharmar\.github\.io\/pharmapkgs");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions"><ul><li><a href="https://github.com/pharmaR/pharmapkgs/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>