project:
    type: website
    resources: []

website:
    title: "Pharmapkgs: riskreports"
    site-url: https://pharmar.github.io/pharmapkgs
    description: List of validated R packages.

    repo-url: https://github.com/pharmaR/pharmapkgs
    repo-actions: [edit, issue]

    open-graph: false

    navbar:
        right:
            - icon: github
              href: https://github.com/pharmaR/pharmapkgs
              aria-label: GitHub repo

format:
    html:
        theme:
            light: [litera, styles.scss]
            dark: [darkly, styles-dark.scss]
        highlight-style: a11y-dark
        mainfont: "Atkinson Hyperlegible"
        code-copy: true
        code-overflow: wrap

editor: visual
