name: Publish website
on:
  workflow_dispatch:
permissions:
    contents: write
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: quarto-dev/quarto-actions/setup@v2
      with:
      version: 1.7.13
    - uses: quarto-dev/quarto-actions/publish@v2
      name: Publish to GitHub Pages (and render)
      with:
      target: gh-pages
      env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
