name: Unit tests

on:
  workflow_dispatch:
  push:

env:
    PHARMAPKGS_REMOTE_REPO:  https://cloud.r-project.org/
    PHARMAPKGS_LIMIT: 5
    PHARMAPKGS_EXCLUDED_METRICS: ${{ vars.PHARMAPKGS_EXCLUDED_METRICS || 'assess_covr_coverage,assess_r_cmd_check' }}
    LOGGER_LOG_LEVEL: DEBUG

jobs:
    main:
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v4
        - uses: r-lib/actions/setup-r@v2
        - uses: quarto-dev/quarto-actions/setup@v2
        - uses: r-lib/actions/setup-r-dependencies@v2
          with:
            extra-packages: any::rcmdcheck
            needs: check

        - uses: r-lib/actions/check-r-package@v2
          with:
            args: 'c("--no-manual")'
