name: Unit tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: ready_for_review

env:
    PHARMAPKGS_REMOTE_REPO: https://raw.githubusercontent.com/r-hub/repos/main
    PHARMAPKGS_LIMIT: 5

jobs:
    main:
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v4
        - uses: r-lib/actions/setup-r@v2
        - uses: quarto-dev/quarto-actions/setup@v2
        - uses: r-lib/actions/setup-r-dependencies@v2

        - name: Run unit tests
          shell: Rscript {0}
          run: devtools::test()
